### ISSUE TITLE
Prácticas compuertas logicas

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/compuertas-logicas-equipo#1]
[PRACTICA DE COMPUERTAS LOGICAS.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo/files/7729844/PRACTICA.DE.COMPUERTAS.LOGICAS.pdf)

**Comment by RicardoMtzSts** [comment]
Portada: (excelente) 25 puntos.
procedimiento: (notable) falto mencionar los materiales usados, faltaron algunos procedimientos de la mayoría de actividades.22puntos
figuras ilustraciones y fotografías: (notable) falto la descripción de la mayoría de actividades.22puntos
resultados y conclusiones: (notable) falto el apartado resultados. 22puntos
total : 91/100
calificación: 27%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
